[julep]
api_key = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YmY1ZDM3MC03ODk4LTVmMTktODBkMS1hNDNjYzkxY2RhOWYiLCJlbWFpbCI6Im1vbmlzaGFrb2xsaXBhcmExM0BnbWFpbC5jb20iLCJpYXQiOjE3NTE2OTYwNzMsImV4cCI6MTc1MjMwMDg3M30.QIz_dIClqaCnVKVt4KHfd4d68FEC6n1c6Z0MEdP6uwS3Uf4c78jKr61nXzlw9QhzBZgikSYlDHgNd3SnXv-A7w"

[weather]
api_key = "9790d903731d40fdae150122243112"

[unsplash]
api_key = "uaOlVkTPqMI2oqoUg9MxLG4osj_3Ai-0kxSK2UlqpPk"



